[[droplet]]
id = 1
name = "auto-nginx 1"
private-ip = "192.168.0.1"
server-host = "192.168.0.1:8080"
health-url = "http://192.168.0.1:8000/index.html"

[[droplet]]
id = 2
name = "auto-nginx 2"
private-ip = "192.168.0.2"
server-host = "192.168.0.2:8080"
health-url = "http://192.168.0.2:8000/index.html"

